name = "MineralEoS"
uuid = "d2c9e738-65c1-4ec6-a6a5-c9a48276562c"
version = "0.1.0"
authors = ["tduretz <duretz@uni-frankfurt.de>"]

[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DifferentiationInterface = "0, 1, 2"
ForwardDiff = "0, 1, 2"
MuladdMacro = "0.2.4"
StaticArrays = "1.9.16"
